/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-frequent-place`; params?: Router.UnknownInputParams; } | { pathname: `/admin-qr`; params?: Router.UnknownInputParams; } | { pathname: `/code`; params?: Router.UnknownInputParams; } | { pathname: `/danger-modal`; params?: Router.UnknownInputParams; } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/facility`; params?: Router.UnknownInputParams; } | { pathname: `/frequent-places`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/ProtectedNotificationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/protector-main`; params?: Router.UnknownInputParams; } | { pathname: `/protector-select`; params?: Router.UnknownInputParams; } | { pathname: `/select-type`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/alarm`; params?: Router.UnknownInputParams; } | { pathname: `/components/HeaderBadge`; params?: Router.UnknownInputParams; } | { pathname: `/components/map-view`; params?: Router.UnknownInputParams; } | { pathname: `/components/map`; params?: Router.UnknownInputParams; } | { pathname: `/components/protected-map`; params?: Router.UnknownInputParams; } | { pathname: `/components/setting`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-frequent-place`; params?: Router.UnknownOutputParams; } | { pathname: `/admin-qr`; params?: Router.UnknownOutputParams; } | { pathname: `/code`; params?: Router.UnknownOutputParams; } | { pathname: `/danger-modal`; params?: Router.UnknownOutputParams; } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/facility`; params?: Router.UnknownOutputParams; } | { pathname: `/frequent-places`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/ProtectedNotificationScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/protector-main`; params?: Router.UnknownOutputParams; } | { pathname: `/protector-select`; params?: Router.UnknownOutputParams; } | { pathname: `/select-type`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/alarm`; params?: Router.UnknownOutputParams; } | { pathname: `/components/HeaderBadge`; params?: Router.UnknownOutputParams; } | { pathname: `/components/map-view`; params?: Router.UnknownOutputParams; } | { pathname: `/components/map`; params?: Router.UnknownOutputParams; } | { pathname: `/components/protected-map`; params?: Router.UnknownOutputParams; } | { pathname: `/components/setting`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-frequent-place${`?${string}` | `#${string}` | ''}` | `/admin-qr${`?${string}` | `#${string}` | ''}` | `/code${`?${string}` | `#${string}` | ''}` | `/danger-modal${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `/facility${`?${string}` | `#${string}` | ''}` | `/frequent-places${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/ProtectedNotificationScreen${`?${string}` | `#${string}` | ''}` | `/protector-main${`?${string}` | `#${string}` | ''}` | `/protector-select${`?${string}` | `#${string}` | ''}` | `/select-type${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/alarm${`?${string}` | `#${string}` | ''}` | `/components/HeaderBadge${`?${string}` | `#${string}` | ''}` | `/components/map-view${`?${string}` | `#${string}` | ''}` | `/components/map${`?${string}` | `#${string}` | ''}` | `/components/protected-map${`?${string}` | `#${string}` | ''}` | `/components/setting${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-frequent-place`; params?: Router.UnknownInputParams; } | { pathname: `/admin-qr`; params?: Router.UnknownInputParams; } | { pathname: `/code`; params?: Router.UnknownInputParams; } | { pathname: `/danger-modal`; params?: Router.UnknownInputParams; } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/facility`; params?: Router.UnknownInputParams; } | { pathname: `/frequent-places`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/ProtectedNotificationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/protector-main`; params?: Router.UnknownInputParams; } | { pathname: `/protector-select`; params?: Router.UnknownInputParams; } | { pathname: `/select-type`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/alarm`; params?: Router.UnknownInputParams; } | { pathname: `/components/HeaderBadge`; params?: Router.UnknownInputParams; } | { pathname: `/components/map-view`; params?: Router.UnknownInputParams; } | { pathname: `/components/map`; params?: Router.UnknownInputParams; } | { pathname: `/components/protected-map`; params?: Router.UnknownInputParams; } | { pathname: `/components/setting`; params?: Router.UnknownInputParams; };
    }
  }
}
